name: CI-CD Pipeline
on:
  push:
    branches:
      -master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codes
        uses: actions/checkout@v3

      - name: Set up JDK 27
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Run Test
        run: mvn test

      - name: Deploy to Heroku
        if: success()
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'senin-heroku-uygulama-adi'  # Heroku’da oluşturduğun app adı
          heroku_email: 'senin-email-adresin@example.com'
